package com.android.odin

enum class PermissionRisk {
    ASTRONOMICAL,
    CRITICAL,
    HIGH,
    LOW,
    MEDIUM,
    NONE,
    UNKNOWN
}

val PERMISSION_RISK_MAP: Map<String, PermissionRisk> = mapOf(
    // ASTRONOMICAL
    "android.permission.INSTALL_PACKAGES" to PermissionRisk.ASTRONOMICAL,

    // CRITICAL
    "android.permission.SYSTEM_CAMERA" to PermissionRisk.CRITICAL,
    "android.permission.COPY_PROTECTED_DATA" to PermissionRisk.CRITICAL,
    "android.permission.WRITE_SECURE_SETTINGS" to PermissionRisk.CRITICAL,
    "android.permission.READ_FRAME_BUFFER" to PermissionRisk.CRITICAL,
    "android.permission.MANAGE_CA_CERTIFICATES" to PermissionRisk.CRITICAL,
    "android.permission.MANAGE_APP_OPS_MODES" to PermissionRisk.CRITICAL,
    "android.permission.GRANT_RUNTIME_PERMISSIONS" to PermissionRisk.CRITICAL,
    "android.permission.DUMP" to PermissionRisk.CRITICAL,
    "android.permission.MANAGE_PROFILE_AND_DEVICE_OWNERS" to PermissionRisk.CRITICAL,
    "android.permission.MOUNT_UNMOUNT_FILESYSTEMS" to PermissionRisk.CRITICAL,
    "android.permission.PROVIDE_DEFAULT_ENABLED_CREDENTIAL_SERVICE" to PermissionRisk.CRITICAL,
    "android.permission.PROVIDE_REMOTE_CREDENTIALS" to PermissionRisk.CRITICAL,
    "android.permission.THREAD_NETWORK_PRIVILEGED" to PermissionRisk.CRITICAL,
    "android.permission.RECORD_SENSITIVE_CONTENT" to PermissionRisk.CRITICAL,
    "android.permission.RECEIVE_SENSITIVE_NOTIFICATIONS" to PermissionRisk.CRITICAL,
    "android.permission.CAMERA" to PermissionRisk.CRITICAL,

    // HIGH
    "android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS" to PermissionRisk.HIGH,
    "android.permission.SEND_SMS_NO_CONFIRMATION" to PermissionRisk.HIGH,
    "android.permission.READ_LOGS" to PermissionRisk.HIGH,
    "android.permission.READ_PRIVILEGED_PHONE_STATE" to PermissionRisk.HIGH,
    "android.permission.LOCATION_HARDWARE" to PermissionRisk.HIGH,
    "android.permission.BIND_ACCESSIBILITY_SERVICE" to PermissionRisk.HIGH,
    "com.android.voicemail.permission.READ_VOICEMAIL" to PermissionRisk.HIGH,
    "android.permission.CAPTURE_AUDIO_OUTPUT" to PermissionRisk.HIGH,
    "android.permission.ACCESS_NOTIFICATIONS" to PermissionRisk.HIGH,
    "android.permission.INTERACT_ACROSS_USERS_FULL" to PermissionRisk.HIGH,
    "android.permission.BLUETOOTH_PRIVILEGED" to PermissionRisk.HIGH,
    "android.permission.GET_PASSWORD" to PermissionRisk.HIGH,
    "android.permission.INTERNAL_SYSTEM_WINDOW" to PermissionRisk.HIGH,
    "android.permission.MANAGE_ONGOING_CALLS" to PermissionRisk.HIGH,
    "android.permission.BIND_AUTOFILL_SERVICE" to PermissionRisk.HIGH,
    "android.permission.WRITE_VERIFICATION_STATE_E2EE_CONTACT_KEYS" to PermissionRisk.HIGH,
    "android.permission.READ_DROPBOX_DATA" to PermissionRisk.HIGH,
    "android.permission.WRITE_FLAGS" to PermissionRisk.HIGH,
    "android.permission.WRITE_SMS" to PermissionRisk.HIGH,
    "android.permission.ACCESS_WIFI_STATE" to PermissionRisk.HIGH,
    "android.permission.READ_RESTRICTED_STATS" to PermissionRisk.HIGH,
    "android.permission.READ_SMS" to PermissionRisk.HIGH,
    "android.permission.RECEIVE_MMS" to PermissionRisk.HIGH,
    "android.permission.RECEIVE_SMS" to PermissionRisk.HIGH,
    "android.permission.ACCESS_FINE_LOCATION" to PermissionRisk.HIGH,
    "android.permission.ACCESS_BACKGROUND_LOCATION" to PermissionRisk.HIGH,
    "android.permission.RECORD_AUDIO" to PermissionRisk.HIGH,

    // MEDIUM
    "android.permission.CHANGE_COMPONENT_ENABLED_STATE" to PermissionRisk.MEDIUM,
    "android.permission.CONNECTIVITY_INTERNAL" to PermissionRisk.MEDIUM,
    "android.permission.SYSTEM_ALERT_WINDOW" to PermissionRisk.MEDIUM,
    "android.permission.INTERACT_ACROSS_USERS" to PermissionRisk.MEDIUM,
    "android.permission.MANAGE_USERS" to PermissionRisk.MEDIUM,
    "android.permission.MANAGE_EXTERNAL_STORAGE" to PermissionRisk.MEDIUM,
    "android.permission.ACCESS_BLOBS_ACROSS_USERS" to PermissionRisk.MEDIUM,
    "android.permission.REGISTER_NSD_OFFLOAD_ENGINE" to PermissionRisk.MEDIUM,
    "android.permission.ACCESS_LAST_KNOWN_CELL_ID" to PermissionRisk.MEDIUM,
    "android.permission.USE_COMPANION_TRANSPORTS" to PermissionRisk.MEDIUM,
    "android.permission.BLUETOOTH_ADMIN" to PermissionRisk.MEDIUM,
    "android.permission.ACCESS_COARSE_LOCATION" to PermissionRisk.MEDIUM,
    "android.permission.READ_CONTACTS" to PermissionRisk.MEDIUM,
    "android.permission.WRITE_CONTACTS" to PermissionRisk.MEDIUM,
    "android.permission.ACCESS_MEDIA_LOCATION" to PermissionRisk.MEDIUM,
    "android.permission.READ_EXTERNAL_STORAGE" to PermissionRisk.MEDIUM,
    "android.permission.WRITE_EXTERNAL_STORAGE" to PermissionRisk.MEDIUM,
    "android.permission.READ_CALL_LOG" to PermissionRisk.MEDIUM,
    "android.permission.WRITE_CALL_LOG" to PermissionRisk.MEDIUM,
    "android.permission.READ_CALENDAR" to PermissionRisk.MEDIUM,
    "android.permission.BODY_SENSORS" to PermissionRisk.MEDIUM,
    "android.permission.BLUETOOTH_ADVERTISE" to PermissionRisk.MEDIUM,
    "android.permission.READ_MEDIA_AUDIO" to PermissionRisk.MEDIUM,
    "android.permission.READ_MEDIA_IMAGES" to PermissionRisk.MEDIUM,
    "android.permission.READ_MEDIA_VIDEO" to PermissionRisk.MEDIUM,

    // LOW
    "android.permission.PACKAGE_USAGE_STATS" to PermissionRisk.LOW,
    "android.permission.MASTER_CLEAR" to PermissionRisk.LOW,
    "android.permission.DEVICE_POWER" to PermissionRisk.LOW,
    "android.permission.READ_PRECISE_PHONE_STATE" to PermissionRisk.LOW,
    "android.permission.LOG_FOREGROUND_RESOURCE_USE" to PermissionRisk.LOW,
    "android.permission.MANAGE_DEFAULT_APPLICATIONS" to PermissionRisk.LOW,
    "android.permission.MANAGE_FACE" to PermissionRisk.LOW,
    "android.permission.REPORT_USAGE_STATS" to PermissionRisk.LOW,
    "android.permission.MANAGE_DISPLAYS" to PermissionRisk.LOW,
    "android.permission.RESTRICT_DISPLAY_MODES" to PermissionRisk.LOW,
    "android.permission.ACCESS_HIDDEN_PROFILES_FULL" to PermissionRisk.LOW,
    "android.permission.GET_BACKGROUND_INSTALLED_PACKAGES" to PermissionRisk.LOW,
    "android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" to PermissionRisk.LOW,
    "android.permission.DELETE_PACKAGES" to PermissionRisk.LOW,
    "android.permission.GET_PACKAGE_SIZE" to PermissionRisk.LOW,
    "android.permission.BLUETOOTH" to PermissionRisk.LOW,

    // NONE
    "android.permission.WRITE_MEDIA_STORAGE" to PermissionRisk.NONE,
    "android.permission.ACCESS_NETWORK_STATE" to PermissionRisk.NONE,
    "android.permission.RECEIVE_BOOT_COMPLETED" to PermissionRisk.NONE,
    "android.permission.WAKE_LOCK" to PermissionRisk.NONE,
    "android.permission.FLASHLIGHT" to PermissionRisk.NONE,
    "android.permission.VIBRATE" to PermissionRisk.NONE,
    "android.permission.MODIFY_AUDIO_SETTINGS" to PermissionRisk.NONE,
)